### ISSUE TITLE
QProcess: Destroyed while process ("python3") is still running.

### ISSUE THREAD

**Issue by MCLiii** [badgerloop-software/sc1-driver-io#46]
Issue on MacOS and WSL Ubuntu, probably caused by QProcess in main for file sync.
Stack got popped after main finished?

**Comment by MCLiii** [comment]
Need to reopen this issue, the qprocess would stall the main process.

**Comment by jackwherry** [comment]
Fixed by #49; this second bug was because ports were in contention, not because of how we spawned the process
